spring:
  application:
    name: transaction-service


  autoconfigure:
      exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  datasource:
    url: jdbc:mysql://localhost:3306/transaction_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: "Raj#2024"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update        # (create, create-drop, update, validate)
    show-sql: true            # Show SQL in console (good for debugging)
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # Optional: Connection pool settings (HikariCP by default)


server:
  port: 8082   # you can change this if needed
